### ISSUE TITLE
Create small scale cosmo simulation

### ISSUE THREAD

**Issue by RatcliffeNCL** [RatcliffeNCL/TidalInferrenceNetwork#1]
Figure out workings of nbodykit to create a toy/example simulation.

**Comment by EiffL** [comment]
So you can take a look at the first section of this tutorial:
https://nbodykit.readthedocs.io/en/latest/cookbook/painting.html
It generates a catalog of "galaxies" using what's called a log normal field, and then puts the galaxies in a cube to get a density field, this is very close to what we want to do.

I would suggest starting a little notebook in a `notebooks` folder to try this out. The goal would essentially be able to generate and then plot such a density field

**Comment by EiffL** [comment]
@RatcliffeNCL any updates on this :-) ?

**Comment by RatcliffeNCL** [comment]
Issue resolved in latest commit.
